// From https://gist.github.com/eegrok/949034 
static const uint16_t MAC_A             = 0x00; // A
static const uint16_t MAC_S             = 0x01; // S
static const uint16_t MAC_D             = 0x02; // D
static const uint16_t MAC_F             = 0x03; // F
static const uint16_t MAC_H             = 0x04; // H
static const uint16_t MAC_G             = 0x05; // G
static const uint16_t MAC_Z             = 0x06; // Z
static const uint16_t MAC_X             = 0x07; // X
static const uint16_t MAC_C             = 0x08; // C
static const uint16_t MAC_V             = 0x09; // V
static const uint16_t MAC_SECTION       = 0x0A; // Section (ISO)
static const uint16_t MAC_B             = 0x0B; // B
static const uint16_t MAC_Q             = 0x0C; // Q
static const uint16_t MAC_W             = 0x0D; // W
static const uint16_t MAC_E             = 0x0E; // E
static const uint16_t MAC_R             = 0x0F; // R
static const uint16_t MAC_Y             = 0x10; // Y
static const uint16_t MAC_T             = 0x11; // T
static const uint16_t MAC_1             = 0x12; // 1
static const uint16_t MAC_2             = 0x13; // 2
static const uint16_t MAC_3             = 0x14; // 3
static const uint16_t MAC_4             = 0x15; // 4
static const uint16_t MAC_6             = 0x16; // 6
static const uint16_t MAC_5             = 0x17; // 5
static const uint16_t MAC_EQUAL         = 0x18; // Equal (=)
static const uint16_t MAC_9             = 0x19; // 9
static const uint16_t MAC_7             = 0x1A; // 7
static const uint16_t MAC_MINUS         = 0x1B; // Minus (-)
static const uint16_t MAC_8             = 0x1C; // 8
static const uint16_t MAC_0             = 0x1D; // 0
static const uint16_t MAC_RIGHT_BRACKET = 0x1E; // Right Bracket (])
static const uint16_t MAC_O             = 0x1F; // O
static const uint16_t MAC_U             = 0x20; // U
static const uint16_t MAC_LEFT_BRACKET  = 0x21; // Left Bracket ([)
static const uint16_t MAC_I             = 0x22; // I
static const uint16_t MAC_P             = 0x23; // P
static const uint16_t MAC_RETURN        = 0x24; // Return (Enter)
static const uint16_t MAC_L             = 0x25; // L
static const uint16_t MAC_J             = 0x26; // J
static const uint16_t MAC_APOSTROPHE    = 0x27; // Apostrophe (')
static const uint16_t MAC_K             = 0x28; // K
static const uint16_t MAC_SEMICOLON     = 0x29; // Semicolon (;)
static const uint16_t MAC_BACKSLASH     = 0x2A; // Backslash (\)
static const uint16_t MAC_COMMA         = 0x2B; // Comma (,)
static const uint16_t MAC_SLASH         = 0x2C; // Slash (/)
static const uint16_t MAC_N             = 0x2D; // N
static const uint16_t MAC_M             = 0x2E; // M
static const uint16_t MAC_PERIOD        = 0x2F; // Period (.)
static const uint16_t MAC_TAB           = 0x30; // Tab
static const uint16_t MAC_SPACE         = 0x31; // Space
static const uint16_t MAC_TILDE         = 0x32; // Tilde (~)
static const uint16_t MAC_DELETE        = 0x33; // Delete (Backspace)
static const uint16_t MAC_ENTER_PB      = 0x34; // Enter (PowerBook)
static const uint16_t MAC_ESC           = 0x35; // Escape
static const uint16_t MAC_RIGHT_CMD     = 0x36; // Right Command
static const uint16_t MAC_LEFT_CMD      = 0x37; // Command (Left)
static const uint16_t MAC_LEFT_SHIFT    = 0x38; // Shift (Left)
static const uint16_t MAC_CAPS_LOCK     = 0x39; // Caps Lock
static const uint16_t MAC_LEFT_OPTION   = 0x3A; // Option (Left)
static const uint16_t MAC_LEFT_CONTROL  = 0x3B; // Control (Left)
static const uint16_t MAC_RIGHT_SHIFT   = 0x3C; // Shift (Right)
static const uint16_t MAC_RIGHT_OPTION  = 0x3D; // Option (Right)
static const uint16_t MAC_RIGHT_CONTROL = 0x3E; // Control (Right)
static const uint16_t MAC_FN            = 0x3F; // Function (Fn)
static const uint16_t MAC_F17           = 0x40; // F17
static const uint16_t MAC_KP_DOT        = 0x41; // Keypad Decimal
static const uint16_t MAC_KP_MULTIPLY   = 0x43; // Keypad Multiply
static const uint16_t MAC_KP_PLUS       = 0x45; // Keypad Plus
static const uint16_t MAC_CLEAR         = 0x47; // Clear
static const uint16_t MAC_VOL_UP        = 0x48; // Volume Up
static const uint16_t MAC_VOL_DOWN      = 0x49; // Volume Down
static const uint16_t MAC_MUTE          = 0x4A; // Mute
static const uint16_t MAC_KP_DIVIDE     = 0x4B; // Keypad Divide
static const uint16_t MAC_KP_ENTER      = 0x4C; // Keypad Enter
static const uint16_t MAC_KP_MINUS      = 0x4E; // Keypad Minus
static const uint16_t MAC_F18           = 0x4F; // F18
static const uint16_t MAC_F19           = 0x50; // F19
static const uint16_t MAC_KP_EQUAL      = 0x51; // Keypad Equal
static const uint16_t MAC_KP_0          = 0x52; // Keypad 0
static const uint16_t MAC_KP_1          = 0x53; // Keypad 1
static const uint16_t MAC_KP_2          = 0x54; // Keypad 2
static const uint16_t MAC_KP_3          = 0x55; // Keypad 3
static const uint16_t MAC_KP_4          = 0x56; // Keypad 4
static const uint16_t MAC_KP_5          = 0x57; // Keypad 5
static const uint16_t MAC_KP_6          = 0x58; // Keypad 6
static const uint16_t MAC_KP_7          = 0x59; // Keypad 7
static const uint16_t MAC_F20           = 0x5A; // F20
static const uint16_t MAC_KP_8          = 0x5B; // Keypad 8
static const uint16_t MAC_KP_9          = 0x5C; // Keypad 9
static const uint16_t MAC_JIS_YEN       = 0x5D; // JIS Yen
static const uint16_t MAC_JIS_UNDERSCORE= 0x5E; // JIS Underscore
static const uint16_t MAC_JIS_KP_COMMA  = 0x5F; // JIS Keypad Comma
static const uint16_t MAC_F5            = 0x60; // F5
static const uint16_t MAC_F6            = 0x61; // F6
static const uint16_t MAC_F7            = 0x62; // F7
static const uint16_t MAC_F3            = 0x63; // F3
static const uint16_t MAC_F8            = 0x64; // F8
static const uint16_t MAC_F9            = 0x65; // F9
static const uint16_t MAC_JIS_EISU      = 0x66; // JIS Eisu
static const uint16_t MAC_F11           = 0x67; // F11
static const uint16_t MAC_JIS_KANA      = 0x68; // JIS Kana
static const uint16_t MAC_F13           = 0x69; // F13
static const uint16_t MAC_F16           = 0x6A; // F16
static const uint16_t MAC_F14           = 0x6B; // F14
static const uint16_t MAC_F10           = 0x6D; // F10
static const uint16_t MAC_MENU_PC       = 0x6E; // PC Menu
static const uint16_t MAC_F12           = 0x6F; // F12
/* 0x70 not found */
static const uint16_t MAC_F15           = 0x71; // F15
static const uint16_t MAC_HELP          = 0x72; // Help
static const uint16_t MAC_HOME          = 0x73; // Home
static const uint16_t MAC_PAGE_UP       = 0x74; // Page Up
static const uint16_t MAC_DEL           = 0x75; // Delete (Forward)
static const uint16_t MAC_F4            = 0x76; // F4
static const uint16_t MAC_END           = 0x77; // End
static const uint16_t MAC_F2            = 0x78; // F2
static const uint16_t MAC_PAGE_DOWN     = 0x79; // Page Down
static const uint16_t MAC_F1            = 0x7A; // F1
static const uint16_t MAC_LEFT          = 0x7B; // Left Arrow
static const uint16_t MAC_RIGHT         = 0x7C; // Right Arrow
static const uint16_t MAC_DOWN          = 0x7D; // Down Arrow
static const uint16_t MAC_UP            = 0x7E; // Up Arrow
static const uint16_t MAC_POWER_PC      = 0x7F; // Power (PC)